### ISSUE TITLE
SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by JoshuaTCooper** [jhcepas/eggnog-mapper#15]
Dear jhcepas, 

I downloaded the github copy, and after setting up the euk database and associated files following the basic instruction, I tried running a test and got this? I'm not sure why its throwing an error?

```
python2.7 ./emapper.py -d euk -i test/polb.fa -out polb_bact_euk
Traceback (most recent call last):
  File "./emapper.py", line 16, in <module>
    from eggnogmapper import search
  File "/home/ubuntu/software/eggnog-mapper/eggnogmapper/search.py", line 20, in <module>
    from . import annota
  File "/home/ubuntu/software/eggnog-mapper/eggnogmapper/annota.py", line 195
    if g and g.split('|')[2] not in excluded_gos])
                                         ^
SyntaxError: invalid syntax
```

**Comment by jhcepas** [comment]
thanks @JoshuaTCooper 
the problem should be fixed in the latest version.
