### ISSUE TITLE
Issue with missing seed_orthologs_file

### ISSUE THREAD

**Issue by meren** [jhcepas/eggnog-mapper#22]
Hi,

I run emapper like this:

```
emapper.py -i aa_sequences.fa --output aa_sequences_eggnog -d bact --no_refine
```

And it crashed like this:

```
#  emapper-0.12.6
# ./emapper.py  -i aa_sequences.fa --output aa_sequences_eggnog -d bact --no_refine
Loading server at localhost, port 51500-51501
26 7.76936841011 3.35 q/s
(...)
32201 8095.21844888 3.98 q/s
32226 8099.19744229 3.98 q/s
32251 8104.59060812 3.98 q/s
(...)
Waiting for server to become ready... localhost 51500
Reading idmap /automounts/workspace/workspace/meren/EGGNOG/eggnog-mapper/data/hmmdb_levels/bact_50/bact_50.hmm.idmap
159207 names loaded
Sequence mapping starts now!
 Processed queries:32265 total_time:8106.77720094 rate:3.98 q/s
Reading HMM matches
Functional annotation of refined hits starts now
Traceback (most recent call last):
  File "/workspace/meren/EGGNOG/eggnog-mapper/emapper.py", line 897, in <module>
    main(args)
  File "/workspace/meren/EGGNOG/eggnog-mapper/emapper.py", line 259, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "/workspace/meren/EGGNOG/eggnog-mapper/emapper.py", line 600, in annotate_hits_file
    for line in open(seed_orthologs_file):
IOError: [Errno 2] No such file or directory: 'aa_sequences_eggnog.emapper.seed_orthologs'
```

Best,

**Comment by PedroBarbosa** [comment]
Hi meren,

How did you solve this issue? I'm facing the same error.
Best,
Pedro

**Comment by jhcepas** [comment]
@PedroBarbosa, thanks for reporting this. are you on the latest version? 
if so, do you have small test case? I can try to debug what is happening

**Comment by PedroBarbosa** [comment]
@jhcepas sorry, it was an input argument issue.
I'm in the latest version, but I was providing the whole path for the hmmer database:

-d ../eggnog-mapper-0.12.7/data/hmmdb_levels/virNOG_hmm/virNOG_hmm.all_hmm

When I just set virNOG, it works, thanks:)
