### ISSUE TITLE
Job failed error?

### ISSUE THREAD

**Issue by lynnetea** [jhcepas/eggnog-mapper#51]
Hello,

I am trying to do a rough annotation on a phage genome, but it keeps failing due to an error found?
I have pasted the information below from what I believe is the error report found in MM_fZ9og3.1.err.txt:     

Traceback (most recent call last):
  File "/home/huerta/emapper_production/emapper.py", line 1082, in <module>
    main(args)
  File "/home/huerta/emapper_production/emapper.py", line 221, in main
    dump_hmm_matches(args.input, hmm_hits_file, dbpath, port, scantype, idmap, args)
  File "/home/huerta/emapper_production/emapper.py", line 382, in dump_hmm_matches
    base_tempdir=args.temp_dir)):
  File "/home/huerta/emapper_production/eggnogmapper/search.py", line 284, in hmmscan
    "Inconsistent qlen when parsing hmmscan output")
ValueError: Inconsistent qlen when parsing hmmscan output
exitcode: 1

Can anyone help me fix this issue? I don't know why I'm getting this error. 
Thank you so much!

**Comment by jhcepas** [comment]
is the error still occurring? We had some overloading problems in our servers, which should be solved now. 
Please reopen this if this is a different problem (and attach an example input file and parameters that allows to reproduce the error). 
Thanks!
