### ISSUE TITLE
errors while  installing the dependencies

### ISSUE THREAD

**Issue by faithoni** [jhcepas/eggnog-mapper#526]
Dear authors,
I tried to install the dependencies for the tool after cloning the github but I get error messages with all three methods. 

**python setup.py install**

check.warn(importable)
Bio/cpairwise2module.c: In function ‘_get_match_score’:
Bio/cpairwise2module.c:58:5: warning: ‘PyEval_CallObjectWithKeywords’ is deprecated [-Wdeprecated-declarations]
   58 |     if(!(py_result = PyEval_CallObject(py_match_fn, py_arglist)))
      |     ^~
In file included from /home/faith/miniconda3/include/python3.12/Python.h:95,
                 from Bio/cpairwise2module.c:14:
/home/faith/miniconda3/include/python3.12/ceval.h:27:43: note: declared here
   27 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Bio/trie.c: In function ‘_with_prefix_helper.constprop’:
Bio/trie.c:595:13: warning: ‘strncat’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  595 |             strncat(current_key, suffix, suffixlen);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Bio/trie.c:561:21: note: length computed here
  561 |         suffixlen = strlen(suffix);
      |                     ^~~~~~~~~~~~~~
Bio/triemodule.c: In function ‘PyInit_trie’:
Bio/triemodule.c:837:25: error: lvalue required as left operand of assignment
  837 |     Py_TYPE(&Trie_Type) = &PyType_Type;
      |                         ^
error: Setup script exited with error: command '/usr/lib64/ccache/gcc' failed with exit code 1

**pip install -r requirements.txt**

 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for biopython
  Running setup.py clean for biopython
Failed to build biopython
ERROR: Could not build wheels for biopython, which is required to install pyproject.toml-based projects

**conda install --file requirements.txt**
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/jlap/fetch.py", line 259, in download_and_hash
        repodata.write(block)
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/jlap/fetch.py", line 218, in write
        return self.backing.write(b)
               ^^^^^^^^^^^^^^^^^^^^^
    OSError: [Errno 122] Disk quota exceeded

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/cli/main.py", line 84, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 200, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/notices/core.py", line 132, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/cli/main_install.py", line 152, in execute
        return install(args, parser, "install")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/cli/install.py", line 377, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/core/solve.py", line 153, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
                                   ^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/core/solve.py", line 222, in solve_for_diff
        final_precs = self.solve_final_state(
                      ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 207, in solve_final_state
        index = IndexHelper(
                ^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda_libmamba_solver/index.py", line 136, in __init__
        self._index = self._load_channels()
                      ^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda_libmamba_solver/index.py", line 332, in _load_channels
        jsons = {url: str(path) for (url, path) in executor.map(self._fetch_channel, urls)}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
        yield _result_or_cancel(fs.pop())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
        return fut.result(timeout)
               ^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/concurrent/futures/_base.py", line 456, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/home/faith/miniconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda_libmamba_solver/index.py", line 254, in _fetch_channel
        json_path, _ = subdir_data.repo_fetch.fetch_latest_path()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/__init__.py", line 749, in fetch_latest_path
        _, state = self.fetch_latest()
                   ^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/__init__.py", line 847, in fetch_latest
        raw_repodata = repo.repodata_parsed(cache.state)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/jlap/interface.py", line 87, in repodata_parsed
        repodata_json_or_none = fetch.request_url_jlap_state(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/jlap/fetch.py", line 309, in request_url_jlap_state
        response = download_and_hash(
                   ^^^^^^^^^^^^^^^^^^
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/jlap/fetch.py", line 257, in download_and_hash
        with writer as repodata:
      File "/home/faith/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/jlap/fetch.py", line 221, in close
        self.backing.close()
    OSError: [Errno 122] Disk quota exceeded

`$ /home/faith/miniconda3/bin/conda install --file requirements.txt`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/faith/miniconda3/bin/conda
             CONDA_PREFIX=/home/faith/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/faith/miniconda3/bin/python
               CONDA_ROOT=/home/faith/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                  MANPATH=/home/faith/.nvm/versions/node/v21.7.3/share/man:/software/lmod/lmod/s
                          hare/man:
               MODULEPATH=/software/skylake/modules/all/Core:/software/modulefiles
                     PATH=/work/faith/eggnog-mapper:/work/faith/eggnog-
                          mapper/eggnogmapper/bin:/home/faith/bin:/home/faith/ncbi-blast-
                          2.14.0+/bin:/home/faith/.nvm/versions/node/v21.7.3/bin:/work/faith/bla
                          st/ncbi-blast-
                          2.15.0+/bin:/home/faith/miniconda3/bin:/home/faith/miniconda3/condabin
                          :/global/local/bin:/global/local/just-dont-bin:/usr/lib64/ccache:/usr/
                          local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lpp/mmfs/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/faith/miniconda3
            shell level : 1
       user config file : /home/faith/.condarc
 populated config files : /home/faith/.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.12.2.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake_avx512
                          __conda=24.5.0=0
                          __glibc=2.34=0
                          __linux=5.14.0=0
                          __unix=0=0
       base environment : /home/faith/miniconda3  (writable)
      conda av data dir : /home/faith/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/faith/miniconda3/pkgs
                          /home/faith/.conda/pkgs
       envs directories : /home/faith/miniconda3/envs
                          /home/faith/.conda/envs
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.32.2 CPython/3.12.2 Linux/5.14.0-284.11.1.el9_2.x86_64 rocky/9.1 glibc/2.34 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 66819:2400
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
Timeout reached. No report sent.

please how can i handle this?
Thank you

**Comment by knarrff** [comment]
Stumbling across this as well. The following from https://docs.python.org/3/c-api/structures.html#c.Py_TYPE might be related:
"_Changed in version 3.11: Py_TYPE() is changed to an inline static function. The parameter type is no longer const PyObject*._"

The issue was opened in biopython: https://github.com/biopython/biopython/issues/4643 and closed March 1 2024. This means the fix should be in version 184 of biopython. Thus, one way to fix this might be by upgrading the dependency on biopython to that version. However, this is only necessary for Python 3.11: users of older versions would not see that problem and might not want the upgrade.

As a sidenote: assuming you have all dependencies already installed, this might help as well:
```
pip install --no-deps eggnog_mapper
```
