### ISSUE TITLE
ValueError in refinement step

### ISSUE THREAD

**Issue by raistlin91** [jhcepas/eggnog-mapper#54]
I got this error in the refinement step:

94500 2044.13207722 46.23 q/s (refinement)
Traceback (most recent call last):
  File "emapper.py", line 1086, in <module>
    main(args)
  File "emapper.py", line 260, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "emapper.py", line 679, in annotate_hits_file
    for result in pool.imap(annotate_hit_line, iter_hit_lines(seed_orthologs_file, args)):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
ValueError: invalid literal for float(): 8.9e-73# Sat Jun 24 10:21:42 2017

**Comment by jhcepas** [comment]
we would need a test example that reproduces the error to debug. Reopen if the problem persists. 
thanks
