### ISSUE TITLE
Database was built with a different version of diamond

### ISSUE THREAD

**Issue by juanvillada** [jhcepas/eggnog-mapper#72]
Hi @jhcepas, thank you for this wonderful tool.

I had an issue when using my local `diamond`. The message from `eggNog-mapper` was:
```
Error: Database was built with a different version of diamond as is incompatible.
Traceback (most recent call last):
  File "emapper.py", line 1001, in <module>
    main(args)
  File "emapper.py", line 216, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "emapper.py", line 353, in dump_diamond_matches
```
I just solved it by removing the local `diamond` from my `$PATH`, and used insted the `diamond` in `eggnog-mapper/bin/diamond`.

Best regards!

**Comment by juanvillada** [comment]
Did not see this before:

https://github.com/jhcepas/eggnog-mapper/issues/48

it is solved.
