### ISSUE TITLE
emapper crashes at functional annotation

### ISSUE THREAD

**Issue by xvazquezc** [jhcepas/eggnog-mapper#91]
Hi @jhcepas ,

Yesterday, I updated eggnog-mapper from source and since then it crashes at the second step, right after printing the `Functional annotation of refined hits starts now` message.

I used to run version 0.99* without problem. I searched in the repo and I found #77 so I re-downloaded all the db just in case with `download_eggnog_data.py`. Still I get the same message.

This is the output:
```
~/eggnog-mapper/emapper.py --cpu 4 -d gproNOG:localhost:51818 -i test.faa -o test
#  emapper-1.0.3-3-g3e22728
# ./emapper.py  --cpu 4 -d gproNOG:localhost:51818 -i test.faa -o test
DB Server already running or not needed!
Reading idmap /home/xabi/eggnog-mapper/data/hmmdb_levels/gproNOG_hmm/gproNOG_hmm.all_hmm.idmap
31711 names loaded
Sequence mapping starts now!
 Processed queries:7 total_time:0.874814033508 rate:8.00 q/s
Hit refinement starts now
 Processed queries:7 total_time:2.83635616302 rate:2.47 q/s
Reading HMM matches
Functional annotation of refined hits starts now
Traceback (most recent call last):
  File "/home/xabi/eggnog-mapper/emapper.py", line 1009, in <module>
    main(args)
  File "/home/xabi/eggnog-mapper/emapper.py", line 269, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "/home/xabi/eggnog-mapper/emapper.py", line 694, in annotate_hits_file
    print >>OUT, '# emapper version:', get_version(), 'emapper DB:', get_db_version()
  File "/home/xabi/eggnog-mapper/eggnogmapper/common.py", line 152, in get_db_version
    annota.db.execute('select * from version;')
sqlite3.OperationalError: no such table: version
```

Python version 2.7.12
Linux xabi-H270-HD3 4.13.0-45-generic \#50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/lib/x86_64-linux-gnu/ld-2.23.so

**Comment by xvazquezc** [comment]
PS: I found out that the version of `eggnog.db` from "latest" is from 2016
http://eggnogdb.embl.de/download/latest/eggnog-mapper-data/

While the 4.5.1, I guess the current based on what `download_eggnog_data.py` was downloading, is from 2017, so the latest is not really the latest(?)
http://eggnogdb.embl.de/download/emapperdb-4.5.1/

**Comment by xvazquezc** [comment]
Solved by downloading the files from  http://eggnogdb.embl.de/download/emapperdb-4.5.1/
